# Generated by Django 4.1.5 on 2023-01-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_logic', '0002_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
